# values-local.yaml
# For local k3s without external domain

quarkus:
  enabled: true
  service:
    type: NodePort  # Use NodePort for local access

golang:
  enabled: true
  service:
    type: NodePort  # Use NodePort for local access

ingress:
  enabled: false  # Disable Ingress for local testing

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: benchmark
  persistence:
    size: 1Gi