global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'quarkus-app'
    static_configs:
      - targets: ['quarkus-app:8080']
        labels:
          app: 'quarkus'
          language: 'kotlin'
    metrics_path: '/q/metrics'
    scrape_interval: 5s

  - job_name: 'golang-app'
    static_configs:
      - targets: ['golang-app:8080']
        labels:
          app: 'golang-gin'
          language: 'go'
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']