{{- if .Values.quarkus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "benchmark.fullname" . }}-quarkus
  labels:
    app: quarkus
    {{ include "benchmark.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.quarkus.replicaCount }}
  selector:
    matchLabels:
      app: quarkus
      {{ include "benchmark.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: quarkus
        {{ include "benchmark.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: quarkus
        image: "{{ .Values.quarkus.image.repository }}:{{ .Values.quarkus.image.tag }}"
        imagePullPolicy: {{ .Values.quarkus.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: QUARKUS_DATASOURCE_JDBC_URL
          {{- if .Values.pgbouncer.enabled }}
          value: "jdbc:postgresql://{{ include "benchmark.fullname" . }}-pgbouncer:5432/{{ .Values.postgresql.auth.database }}"
          {{- else }}
          value: "jdbc:postgresql://{{ include "benchmark.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
          {{- end }}
        - name: QUARKUS_DATASOURCE_USERNAME
          value: "{{ .Values.postgresql.auth.username }}"
        - name: QUARKUS_DATASOURCE_PASSWORD
          value: "{{ .Values.postgresql.auth.password }}"
        - name: QUARKUS_DATASOURCE_JDBC_MAX_SIZE
          value: "{{ .Values.quarkus.dbMaxSize }}"
        - name: QUARKUS_DATASOURCE_JDBC_MIN_SIZE
          value: "{{ .Values.quarkus.dbMinSize }}"
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          {{- toYaml .Values.quarkus.resources | nindent 10 }}
{{- end }}
