{{- if and .Values.postgresql.enabled .Values.pgbouncer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "benchmark.fullname" . }}-pgbouncer
  labels:
    app: pgbouncer
    {{- include "benchmark.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: pgbouncer
    protocol: TCP
    name: pgbouncer
  selector:
    app: pgbouncer
    {{- include "benchmark.selectorLabels" . | nindent 4 }}
{{- end }}