{{- if and .Values.postgresql.enabled .Values.pgbouncer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "benchmark.fullname" . }}-pgbouncer
  labels:
    app: pgbouncer
    {{- include "benchmark.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pgbouncer.replicaCount }}
  selector:
    matchLabels:
      app: pgbouncer
      {{- include "benchmark.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: pgbouncer
        {{- include "benchmark.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: pgbouncer
        image: {{ .Values.pgbouncer.image.repository }}:{{ .Values.pgbouncer.image.tag }}
        imagePullPolicy: {{ .Values.pgbouncer.image.pullPolicy }}
        ports:
        - name: pgbouncer
          containerPort: {{ .Values.pgbouncer.listenPort }}
          protocol: TCP
        env:
        - name: DB_USER
          value: {{ .Values.postgresql.auth.username | quote }}
        - name: DB_PASSWORD
          value: {{ .Values.postgresql.auth.password | quote }}
        - name: DB_HOST
          value: {{ include "benchmark.fullname" . }}-postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: {{ .Values.postgresql.auth.database | quote }}
        - name: AUTH_TYPE
          value: "md5"
        - name: ADMIN_USERS
          value: {{ .Values.postgresql.auth.username | quote }}
        - name: LISTEN_PORT
          value: {{ .Values.pgbouncer.listenPort | quote }}
        - name: POOL_MODE
          value: {{ .Values.pgbouncer.poolMode | quote }}
        - name: MAX_CLIENT_CONN
          value: {{ .Values.pgbouncer.maxClientConn | quote }}
        - name: DEFAULT_POOL_SIZE
          value: {{ .Values.pgbouncer.defaultPoolSize | quote }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.pgbouncer.listenPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: {{ .Values.pgbouncer.listenPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          {{- toYaml .Values.pgbouncer.resources | nindent 10 }}
{{- end }}