{{- if .Values.quarkusNative.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "benchmark.fullname" . }}-quarkus-native
  labels:
    app: quarkus-native
    release: mon
    {{- include "benchmark.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: quarkus-native
      {{- include "benchmark.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /q/metrics
    interval: 5s
{{- end }}